### ISSUE TITLE
Cannot compile stecs-derive with Darling 0.20.11

### ISSUE THREAD

**Issue by Ultrasquid9** [geng-engine/ecs#14]
After updating Darling to 0.20.11, Stecs no longer compiles:
```
> cargo run

   Compiling stecs-derive v0.1.1
error[E0433]: failed to resolve: could not find `syn` in the list of imported crates
  --> /var/home/ultrasquid/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/stecs-derive-0.1.1/src/split.rs:14:12
   |
14 |     debug: Option<()>,
   |            ^^^^^^ could not find `syn` in the list of imported crates
   |
help: consider importing this crate through its public re-export
   |
1  + use crate::syn;
   |

error[E0433]: failed to resolve: could not find `syn` in the list of imported crates
  --> /var/home/ultrasquid/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/stecs-derive-0.1.1/src/split.rs:15:12
   |
15 |     clone: Option<()>,
   |            ^^^^^^ could not find `syn` in the list of imported crates
   |
help: consider importing this crate through its public re-export
   |
1  + use crate::syn;
   |

error[E0433]: failed to resolve: could not find `syn` in the list of imported crates
  --> /var/home/ultrasquid/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/stecs-derive-0.1.1/src/split.rs:23:13
   |
23 |     nested: Option<()>,
   |             ^^^^^^ could not find `syn` in the list of imported crates
   |
help: consider importing this crate through its public re-export
   |
1  + use crate::syn;
   |

For more information about this error, try `rustc --explain E0433`.
error: could not compile `stecs-derive` (lib) due to 3 previous errors
```

Darling 0.20.10 seems to have the correct behavior. 

Possibly relevant: https://github.com/TedDriggs/darling/issues/333

**Comment by Nertsal** [comment]
Thanks for letting me know, I fixed this and pushed the new v0.1.2 version. Not sure what the issue is exactly, but adding syn as a dependency fixed it.
